### ISSUE TITLE
Symbols on the statusline do not show up

### ISSUE THREAD

**Issue by gauravsatish** [ayesumit/Nvimfy#12]
Some characters do not show up leaving me with weird boxes in their places

![image](https://user-images.githubusercontent.com/59788284/153906712-ed3fe42d-0d6b-4792-b5de-2402bb0dfdf6.png)

this also happens on the bufferline

![image](https://user-images.githubusercontent.com/59788284/153906810-70625366-58ef-4664-ab2c-28bfddb0161b.png)

**Comment by ayesumit** [comment]
U need to use a custom patched font.

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts

**Comment by ayesumit** [comment]
I personally recommend 
[JetbrainsMono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete.ttf)

Or u can have a look on these font libraries
[Rests](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts)
